function z(c){this.onready=this.onfail=this.onsuccess=this.cacheBuster=this.suppressAlert=this.password=this.user=this.async=this.url=this.reqData=this.postData=this.method=null;this.headers={};this.params=null;this.sendAsBinary=true;var b=this.overrideMimeType=null,a=null,d=null,e=null,h=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert,f=this;if(typeof c=="object")for(var i in c){if(typeof this[i]!="undefined")this[i]=c[i]}else this.url=c;if(window.XMLHttpRequest)b=new XMLHttpRequest;
else if(window.ActiveXObject)b=new ActiveXObject("Microsoft.XMLHTTP");else{h("Ajax request error: Unsupported browser.");return}this.send=this.send=function(){function g(){if(b.readyState==4){a=b.status===0?w?"Request aborted.":"Request failed. Check the browser console for more details.":b.status+" - "+b.statusText;f.onready!=null&&f.onready(f);if(b.status==200){d=true;f.onsuccess!=null&&f.onsuccess(f)}else{d=false;f.suppressAlert!=true&&h(a);f.onfail!=null&&f.onfail(f)}e=false}}var j=null,n=null,
k=null;if(f.method==null)j="GET";else if(typeof f.method!="string"&&(f.method.toUpperCase()!="GET"||f.method.toUpperCase()!="POST"||f.method.toUpperCase()!="PUT"||f.method.toUpperCase()!="DELETE")){h('Invalid value for property: "method".');return}else j=f.method.toUpperCase();if(j=="POST"||j=="PUT"||j=="DELETE"){if(f.reqData!=null)k=f.reqData;else if(f.postData!=null)k=f.postData;if(k!=null){if(typeof k!="string"){h('Invalid value for property: "postData".');return}}else k=""}if(f.async==null)n=
true;else if(f.async!=true&&f.async!=false){h('Invalid value for property: "async".');return}else n=f.async;if(typeof f.url!="string")h('Invalid value for property: "url".');else{if(f.user!=null)if(typeof f.user!="string"){h('Invalid value for property: "user".');return}if(f.password!=null)if(typeof f.password!="string"){h('Invalid value for property: "password".');return}if(f.onsuccess!=null)if(typeof f.onsuccess!="function"){h('Invalid value for event: "onsuccess".');return}if(f.onfail!=null)if(typeof f.onfail!=
"function"){h('Invalid value for event: "onfail".');return}if(f.onready!=null)if(typeof f.onready!="function"){h('Invalid value for event: "onready".');return}var s=true;if(k!=null)for(var p in f.headers)if(p.toUpperCase()=="CONTENT-TYPE")if(f.headers[p].toLowerCase().indexOf("www-form-urlencoded")==-1)s=false;var l=f.url,o=f.params;if(typeof o=="object"){var m="";for(p in o){var r=o[p],q=[];if(typeof r=="object"){if(r.length!=null&&r.length>0)q=r}else q.push(r);for(r=0;r<q.length;r++){if(m!="")m+=
"&";m+=encodeURIComponent(p)+"="+encodeURIComponent(q[r])}}if(m!="")if(s&&(j=="POST"||j=="PUT"||j=="DELETE")){if(k!=null&&k!="")k+="&";else k="";k+=m}else{s=l.split("?");if(s.length==2&&s[1]!="")l=s[0]+"?"+s[1]+"&"+m;else l+="?"+m}}if(j==="GET"&&(f.cacheBuster===null||f.cacheBuster===true))l=pui.addUrlCacheBuster(l);try{typeof f.user=="string"&&typeof f.password=="string"?b.open(j,l,n,f.user,f.password):b.open(j,l,n);l=false;var u=f.headers;for(p in u){b.setRequestHeader(p,u[p]);if(p.toUpperCase()==
"CONTENT-TYPE")l=true}if(j=="POST"||j=="PUT"||j=="DELETE")l||b.setRequestHeader("Content-type","application/x-www-form-urlencoded");typeof f.overrideMimeType=="string"&&typeof b.overrideMimeType=="function"&&b.overrideMimeType(f.overrideMimeType)}catch(v){h(v);return}e=true;var w=false;if(n==true){b.onload=g;b.onerror=g;b.onabort=function(){w=true;g()}}if(f.sendAsBinary==true)try{b.sendAsBinary(k)}catch(E){b.send(k)}else b.send(k);n!=true&&g()}};this.ok=this.M=function(){return d!=null?d:false};this.getResponseText=
this.e=function(){return b.responseText};this.getResponseXML=this.u=function(){return b.responseXML};this.getStatus=this.c=function(){return b.status};this.getStatusText=this.l=function(){return b.statusText};this.getStatusMessage=this.v=function(){return a};this.getAllResponseHeaders=this.getAllResponseHeaders=function(){if(d)try{return b.getAllResponseHeaders()}catch(g){h(g)}};this.getResponseHeader=this.getResponseHeader=function(g){if(d)try{return b.getResponseHeader(g)}catch(j){h(j)}};this.setRequestHeader=
this.setRequestHeader=function(g,j){f.headers[g]=j};this.abort=this.abort=function(){if(e===true)try{b.abort()}catch(g){h(g)}}}function A(c,b){var a,d,e,h="";if(arguments.length==1&&typeof arguments[0]=="object"){a=arguments[0];a.async=null;a.onsuccess=null;if(typeof a.handler=="function"){d=true;e=a.handler}else d=false}else if(b!=null&&typeof b=="function"){d=true;e=b}else d=false;a=new z(arguments[0]);a.async=d;a.onsuccess=function(f){h+=f.e();d==true&&e(h)};a.send();if(d==false)return h}
function C(c,b){var a,d,e,h=null,f=false;if(arguments.length==1&&typeof arguments[0]=="object"){a=arguments[0];a.async=null;a.onsuccess=null;if(a.saveResponse==true)f=true;if(typeof a.handler=="function"){d=true;e=a.handler}else d=false}else if(b!=null&&typeof b=="function"){d=true;e=b}else d=false;a=new z(arguments[0]);a.async=d;a.onsuccess=function(i){i=i.e();if(f&&typeof pui=="object")pui.savedJSON=i;try{h=eval("("+i+")")}catch(g){e(null,g);return}d==true&&e(h)};a.send();if(d==false)return h}
if(typeof window.pui=="undefined")window.pui={};window.RPGspRequest=z;window.pui.Ajax=z;window.pui.AjaxRequest=z;window.ajax=A;
window.ajaxXML=function(c,b){var a,d,e,h=null;if(arguments.length==1&&typeof arguments[0]=="object"){a=arguments[0];a.async=null;a.onsuccess=null;a.onfail=null;a.onsuccess=null;if(typeof a.handler=="function"){d=true;e=a.handler}else d=false}else if(b!=null&&typeof b=="function"){d=true;e=b}else d=false;a=new z(arguments[0]);a.async=d;a.onsuccess=function(f){h=f.u();d==true&&e(h)};a.send();if(d==false)return h};window.ajaxJSON=C;
window.ajaxSubmit=function(c,b){var a,d="",e=typeof pui!="undefined"&&typeof pui.alert!="undefined"?pui.alert:alert;if(typeof c=="object")a=c;else{a=document.getElementById(c);if(a==null)a=document.forms[c]}var h;if(a!=null)h=a.tagName;if(a==null||h==null||h.toUpperCase()!="FORM"){e("Ajax request error: Invalid form object.");return""}if(c.action==""){e("Ajax request error: Invalid form action.");return""}for(e=0;e<a.elements.length;e++){h=a.elements[e];if(h.name!=null&&h.name!=""){var f=false;if(h.tagName==
"INPUT"){var i=h.type;i=i.toLowerCase();if(i=="hidden")f=true;if(i=="password")f=true;if(i=="text")f=true;if(pui.ma(i))f=true;if(i=="")f=true;if(i=="checkbox"||i=="radio")if(h.checked)f=true}if(h.tagName=="TEXTAREA")f=true;if(h.tagName=="SELECT")f=true;if(f){if(d!="")d+="&";d+=h.name+"="+encodeURIComponent(h.value)}}}a=new z(a.action);a.method="POST";a.postData=d;var g="",j;if(b!=null&&typeof b=="function")j=true;else{j=false;a.async=false}a.onsuccess=function(n){g+=n.e();j==true&&b(g)};a.send();
if(j==false)return g};function D(c,b){var a,d;a=c!=null&&typeof c=="object"?c:document.getElementById(c);if(a==null)return"";d="";if(a.tagName.toLowerCase()=="div"){d=a.firstChild;d=d!=null&&d.tagName!=null&&d.tagName=="A"?d.innerHTML:a.innerHTML}if(a.tagName=="INPUT"&&a.type=="checkbox"){if(a.checked&&a.i!=null)return a.i;if(!a.checked&&a.T!=null)return a.T;return a.checked}if(a.tagName=="INPUT"&&a.type=="radio")return a.checked;if(a.tagName=="TEXTAREA")d=a.value;else if(a.tagName=="INPUT"){var e=a.B;if(b&&e!=null&&typeof e.value===
"string")if(e.value.length>0)d=a.B.value;else{if(pui["force auto complete match"]==false)d=a.value}else d=a.value}else if(a.tagName=="SELECT"){d=a.selectedIndex;d=d>=0?a.options[d].value:a.pui&&a.pui.properties&&a.pui.properties.value?a.pui.properties.value:a.value}if(a.comboBoxWidget!=null)d=a.comboBoxWidget.getValue();if(a.g!=null)d=a.g.getValue();if(a.z!=null)d=String(a.value);if(a.f!=null){d="";if(a.f.J&&a.f.N!=null)d=a.f.N;else if(!a.f.J&&a.f.L!=null)d=a.f.L}if(a.pui&&a.pui.widget&&typeof a.pui.widget.getPropertyValue===
"function")d=a.pui.widget.getPropertyValue("value");for(d=d.replace(/&nbsp;/g," ");d.indexOf(String.fromCharCode(160))!=-1;)d=d.replace(String.fromCharCode(160)," ");if(d==a.fa)d="";return d}function H(c){if(typeof c!=="string")return c;for(;c.charAt(0)==" ";)c=c.replace(c.charAt(0),"");return c}function I(c){if(typeof c!=="string")return c;return c.replace(/^\s*|\s*$/g,"")}pui.detachCalendar=function(c){if(typeof c=="string")c=document.getElementById(c);c!=null&&pui.qa(c)};
function J(c,b,a){var d=false,e=location.href;e=e.split("?")[0];e=e.split("/");if(e.length>2&&e[e.length-2].toLowerCase()=="auth")d=true;e="/profoundui/";var h=["PUI0009101.PGM","PUI0009102.PGM","PUI0009103.PGM","PUI0009104.PGM","PUI0009107.PGM","PUI0009109.PGM","PUI0009110.PGM","PUI0009119.PGM"];if(typeof pui.widgetURLPrefix==="string"&&h.indexOf(c.toUpperCase())!=-1){e=pui.widgetURLPrefix;if(e.substr(e.length-1)!="/")e+="/"}if(d==true||a==true)e+="auth/";e+=c;if(b!=null&&b==true)e+="/"+PSID;if(pui.serverURL!=
null)e=pui.serverURL+e;return e}pui.getProgramURL=J;pui.ha=function(c){return pui.t(c).x};pui.ia=function(c){return pui.t(c).y};
pui.t=function(c){c=c||window.event;var b={x:0,y:0};if(c!=null&&c.touches!=null&&c.touches.length==1){b.x=c.touches[0].pageX;b.y=c.touches[0].pageY}else if(c!=null){if(c.pageX)b.x=c.pageX;else if(c.clientX)b.x=c.clientX+(document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft);if(c.pageY)b.y=c.pageY;else if(c.clientY)b.y=c.clientY+(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop)}return b};
function K(){var c={},b="";b=location.search.substring(1,location.search.length);if(b.length==0)return c;b=b.replace(/\+/g," ");b=b.split("&");for(var a=0;a<b.length;a++){var d=b[a].split("="),e=decodeURIComponent(d[0]),h="";if(d.length==2)h=decodeURIComponent(d[1]);c[e]=h}return c}if(typeof applyDesignProperty!="undefined")window.X=applyDesignProperty;
pui.p={s:function(c){for(var b="",a=0;a<c.length;a++){var d=c.charCodeAt(a);if(d<128)b+=String.fromCharCode(d);else{if(d>127&&d<2048)b+=String.fromCharCode(d>>6|192);else{b+=String.fromCharCode(d>>12|224);b+=String.fromCharCode(d>>6&63|128)}b+=String.fromCharCode(d&63|128)}}return b},r:function(c){for(var b="",a=0,d=c1=c2=0;a<c.length;){d=c.charCodeAt(a);if(d<128){b+=String.fromCharCode(d);a++}else if(d>191&&d<224){c2=c.charCodeAt(a+1);b+=String.fromCharCode((d&31)<<6|c2&63);a+=2}else{c2=c.charCodeAt(a+
1);c3=c.charCodeAt(a+2);b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63);a+=3}}return b}};
pui.W={b:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",s:function(c){var b="",a,d,e,h,f,i,g=0;for(c=pui.p.s(c);g<c.length;){a=c.charCodeAt(g++);d=c.charCodeAt(g++);e=c.charCodeAt(g++);h=a>>2;a=(a&3)<<4|d>>4;f=(d&15)<<2|e>>6;i=e&63;if(isNaN(d))f=i=64;else if(isNaN(e))i=64;b=b+this.b.charAt(h)+this.b.charAt(a)+this.b.charAt(f)+this.b.charAt(i)}return b},r:function(c){var b="",a,d,e,h,f,i=0;for(c=c.replace(/[^A-Za-z0-9\+\/\=]/g,"");i<c.length;){a=this.b.indexOf(c.charAt(i++));d=
this.b.indexOf(c.charAt(i++));h=this.b.indexOf(c.charAt(i++));f=this.b.indexOf(c.charAt(i++));a=a<<2|d>>4;d=(d&15)<<4|h>>2;e=(h&3)<<6|f;b+=String.fromCharCode(a);if(h!=64)b+=String.fromCharCode(d);if(f!=64)b+=String.fromCharCode(e)}return b=pui.p.r(b)}};
pui.downloadJSON=function(){if(pui.savedJSON==null)pui.alert("JSON is not available.");else{var c=pui.savedJSON;if(typeof JSON==="object"&&typeof JSON.parse==="function"&&typeof JSON.stringify==="function")try{c=JSON.stringify(JSON.parse(pui.savedJSON),null,"  ")}catch(b){}pui.ea("text/plain","json.txt",c)}};
pui.keepAlive=function(){var c;if(!(context=="genie"&&pui.d.h==true)){if(context=="dspf")c=pui.d==null?J("PUI0001200.pgm"):J("PUI0002110.pgm");else if(context=="genie")c=DOCUMENT_URI;else return false;if(pui.psid!=null&&pui.psid!="")c+="/"+pui.psid;if(pui.overrideSubmitUrl!=null&&typeof pui.overrideSubmitUrl=="function")try{c=pui.overrideSubmitUrl(c)}catch(b){}if(context=="genie")pui.A(pui.d.h=true);if(context=="dspf")pui.o=false;pui.ta();var a={keepalive:"1"};if(pui.isCloud)a.workspace_id=pui.cloud.ws.id;
A({url:c,method:"post",params:a,sendAsBinary:false,suppressAlert:true,handler:function(){pui.H();if(context=="genie")pui.A(pui.d.h=false);if(context=="dspf")pui.o=true;for(var d=0;d<pui.m.length;d++)pui.m[d].unMask()},onfail:function(d){pui.onoffline==null&&!pui["suppress comm errors"]&&pui.alert(pui.ja(d));pui.H();if(context=="genie")pui.A(pui.d.h=false);if(context=="dspf")pui.o=true;for(d=0;d<pui.m.length;d++)pui.m[d].unMask();pui.onoffline!=null&&pui.onoffline()}});return true}};
pui.getWindowSize=function(){var c,b;if(document.body&&document.body.offsetWidth){c=document.body.offsetWidth;b=document.body.offsetHeight}if(document.compatMode=="CSS1Compat"&&document.documentElement&&document.documentElement.offsetWidth){c=document.documentElement.offsetWidth;b=document.documentElement.offsetHeight}if(window.innerWidth&&window.innerHeight){c=window.innerWidth;b=window.innerHeight}if(window.visualViewport&&window.visualViewport.width&&window.visualViewport.height){c=window.visualViewport.width;
b=window.visualViewport.height}if(document.documentElement&&document.documentElement.clientWidth){c=document.documentElement.clientWidth;b=document.documentElement.clientHeight}if(c==null&&screen!=null)c=screen.width;if(b==null&&screen!=null)b=screen.height;if(c==null)c=800;if(b==null)b=600;return{width:c,height:b}};pui.openURL=function(c){window.open(c)};
pui.normalizeURL=function(c,b){if(c==null||typeof c!="string")return"";if(b==true&&window.puiMobileClient==null)return c;if(c.substr(0,5).toLowerCase()=="http:"||c.substr(0,6).toLowerCase()=="https:"||c.substr(0,5).toLowerCase()=="data:")return c;return pui.serverURL!=null?pui.serverURL+c:window.cordova&&c.substr(0,1)=="/"?c.substr(1):c};
pui.animate=function(c){var b=c.element;if(typeof b=="string")b=document.getElementById(b);if(b!=null){var a,d=c.effect;if(d=="fly in left"||d=="fly in right"||d=="fly out left"||d=="fly out right")a="left";else if(d=="fly in up"||d=="fly in down"||d=="fly out up"||d=="fly out down")a="top";else if(d=="fade in"||d=="fade out")a="opacity";else{a=c.properties;if(a==null){a=c.property;if(a==null)return}}if(typeof a=="string")a=[a];var e=c.duration;if(e==null)e="500ms";if(e.substr(e.length-1,1)!="s")e+=
"s";var h=parseInt(e)*1E3;if(e.length>2&&e.substr(e.length-2,2)=="ms")h=parseInt(e);var f=c.type;if(f==null)f="ease";var i=c.from,g=c.to;switch(d){case "fly in right":i=-b.offsetWidth;i+="px";g="0px";break;case "fly in left":i=b.offsetWidth;i+="px";g="0px";break;case "fly out left":g=-b.offsetWidth;g+="px";i="0px";break;case "fly out right":g=b.offsetWidth;g+="px";i="0px";break;case "fly out down":g=b.offsetHeight;g+="px";i="0px";break;case "fly out up":g=-b.offsetHeight;g+="px";i="0px";break;case "fly in up":i=
b.offsetHeight;i+="px";g="0px";break;case "fly in down":i=-b.offsetHeight;i+="px";g="0px";break;case "fade in":i="0";g="100";break;case "fade out":i="100";g="0";break}if(g!=null){var j="";for(d=0;d<a.length;d++){var n=a[d];if(j!="")j+=", ";j+=n+" "+e+" "+f}var k=["transition","MozTransition","WebkitTransition","msTransition","OTransition"];if(i!=null){if(typeof i=="string"||typeof i=="number")i=[i];for(d=0;d<a.length;d++){n=a[d];b.style[n]=i[d]}}setTimeout(function(){for(var s=0;s<k.length;s++)b.style[k[s]]=
j;setTimeout(function(){if(typeof g=="string"||typeof g=="number")g=[g];for(var p=0;p<a.length;p++)b.style[a[p]]=g[p];setTimeout(function(){for(var l=0;l<k.length;l++)b.style[k[l]]="";c.oncomplete!=null&&c.oncomplete()},h)},1)},1)}}};pui.getActiveElement=function(){return context=="genie"?lastActiveElement:pui.activeElement};pui.fieldExit=function(c){var b=pui.getActiveElement();if(b!=null){var a=false;if(c!=null)a=true;context=="genie"?fieldExit(b,a):pui.ca(b)}};
pui.gotoNextElement=function(c){O(c,true)};pui.gotoPreviousElement=function(c){O(c,false)};
function O(c,b){var a=b?1:-1,d=document.querySelectorAll("INPUT,SELECT,TEXTAREA"),e=d.length;if(!(e<2))for(var h=Array.prototype.indexOf.call(d,c),f=h+a,i;;){if(f===h)break;if(f===e)f=0;else if(f===-1)f=e-1;else{var g=i=d[f];if(i!=null&&i.comboBoxWidget!=null)g=i.comboBoxWidget.F();if(i!=null&&i.g!=null)g=i.g.F();if(g.readOnly||g.disabled||g.style.visibility==="hidden"||g.tabIndex==="-1"||!g.clientHeight||!g.clientWidth)f+=a;else{try{g.focus();if(document.activeElement!=g){f+=a;continue}setTimeout(function(){pui["highlight on focus"]&&
typeof g.select=="function"&&g.select();pui.sa(null,g)},0)}catch(j){}break}}}}pui.showCalendar=function(c){var b=c;if(typeof c=="string")b=document.getElementById(c);if(b!=null)if(typeof b=="object"){var a=b.calimg;if(a!=null)if(a.click!=null&&typeof a.click=="function")a.click();else a.onclick!=null&&typeof a.onclick=="function"&&setTimeout(function(){a.onclick()},250)}};
pui.getComputedStyle=function(c){var b=null;if(window.getComputedStyle)b=window.getComputedStyle(c);else if(c.currentStyle)b=c.currentStyle;return b};
pui.upload=function(c,b){var a=c.dir,d=c.overwrite===true,e;if(typeof c.slimit=="number")e=c.slimit;var h;if(typeof c.flimit=="number")h=c.flimit;var f="";if(typeof c.altname=="string")f=c.altname;var i;if(typeof c.allowedTypes&&c.allowedTypes instanceof Array)i=c.allowedTypes;if(h==null)h=c.files.length;if(e==null||i==null){for(var g,j=[],n=0;n<c.files.length;n++){var k=c.files[n],s=typeof k.type!="undefined"&&k.type!=""?k.type:"application/octet-stream";pui.Y(j,s)==-1&&j.push(s);k=k.data&&k.data instanceof
ArrayBuffer?k.data.byteLength:k.size;k=Math.ceil(k/1048576);if(g==null||k>g)g=k}if(e==null)e=g;if(i==null)i=j}g=J("PUI0009109.PGM");g+="?AUTH="+encodeURIComponent(pui.n?pui.n:pui.appJob.auth);if(c.mode!=="widget")g+="&mode=ajax";if(c.id)g+="&id="+encodeURIComponent(c.id);g+="&r="+Math.floor(Math.random()*1E9);if(pui.isCloud)g+="&workspace_id="+pui.cloud.ws.id;j=new FormData;j.append("dir",a);j.append("overwrite",d?"1":"0");j.append("flimit",h);j.append("slimit",e);j.append("altname",f);typeof c.generateNames==
"string"&&j.append("generateNames",c.generateNames);for(n=0;n<i.length;n++)j.append("type",i[n]);for(n=0;n<c.files.length;n++){k=c.files[n];if(k.data&&k.data instanceof ArrayBuffer){var p;try{p=new Blob([k.data])}catch(l){a=new window.WebKitBlobBuilder;a.append(k.data);p=a.getBlob()}j.append("file",p)}else j.append("file",k);j.append("filename",k.name)}var o=new XMLHttpRequest;o.open("POST",g,true);o.onreadystatechange=function(){if(o.readyState==4){var m=true,r;if(o.status==200){var q;try{q=eval("("+
o.responseText+")")}catch(u){m=false;r="Server response missing or invalid."}if(q){m=q.success;if(!m)if(q.key){r=pui.getLanguageText("runtimeMsg","upload "+q.key);if(q.key=="file limit")r=r.replace("&1",h);if(q.key=="size limit")r=r.replace("&1",e)}else r=q.error}}else{m=false;r=o.status+" - "+o.statusText+"."}typeof b=="function"&&b(m,r)}};if(typeof c.onabort=="function")o.onabort=c.onabort;if(typeof c.onprogress=="function"&&"upload"in o)o.upload.onprogress=c.onprogress;if(typeof c.onload=="function")o.onload=
c.onload;o.send(j);return o};pui.getCookie=function(c){var b=document.cookie.split(";"),a="",d="",e="",h="";for(h=0;h<b.length;h++){a=b[h].split("=");d=a[0].replace(/^\s+|\s+$/g,"");if(d==c){if(a.length>1)e=unescape(a[1].replace(/^\s+|\s+$/g,""));return e}}return null};
pui.setCookie=function(c,b,a,d,e,h,f){var i=new Date;i.setTime(i.getTime());if(a)a=a*1E3*60*60*24;i=new Date(i.getTime()+a);document.cookie=c+"="+escape(b)+(a?";expires="+i.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(h?";secure":"")+(f?";SameSite="+f:"")};pui.deleteCookie=function(c,b,a,d,e){if(pui.getCookie(c))document.cookie=c+"="+(b?";path="+b:"")+(a?";domain="+a:"")+";expires=Thu, 01-Jan-1970 00:00:01 GMT"+(d?";Secure":"")+(e?";SameSite="+e:"")};
pui.refresh=function(c){if(c==null)c={};var b=c.url;c=c.skin;pui.setCookie("puiRefreshId",pui.psid,null,"/",null,null,"Strict");pui.skipConfirm=true;pui.shutdownOnClose=false;pui.confirmOnClose=false;if(c!=null){c="skin="+encodeURIComponent(c);b=window.location.href;var a=b.split("?");b=a[0];a=a[1];if(a==null)a="";a=a.split("&");for(var d=false,e=0;e<a.length;e++)if(a[e].length>=5&&a[e].substr(0,5).toLowerCase()=="skin="){a[e]=c;d=true}if(!d)if(a.length==1&&a[0]=="")a[0]=c;else a.push(c);a=a.join("&");
b=b+"?"+a}if(b!=null)window.location.href=b;else window.location.reload()};
pui.downloadURL=function(c){if(pui==null||pui.appJob==null||pui.appJob.auth==null||pui.appJob.auth=="")return pui.is_ie?"":"data:text/html,<!DOCTYPE html><html><body><p>To download, please connect to a Profound UI session.</p></body></html>";var b=c.inline===true;if(c.id==null)return"";var a=J("PUI0009110.PGM");a+="?id="+encodeURIComponent(c.id);if(c.contentType!=null)a+="&type="+encodeURIComponent(c.contentType);if(b)a+="&inline=1";a+="&usehttprc=0";a+="&AUTH="+encodeURIComponent(pui.n?pui.n:pui.appJob.auth);
a+="&r="+Math.floor(Math.random()*1E9);return a};pui.download=function(c){var b=pui.downloadURL(c);c=c.inline===true;if(pui==null||pui.appJob==null||pui.appJob.auth==null||pui.appJob.auth=="")c=true;c?pui.openURL(b):pui.link(b)};
pui.focusOnContainer=function(){window.parent!=window&&pui.V(window.parent)&&window.parent.noderun||setTimeout(function(){if(pui.a==null){pui.a=document.createElement("input");pui.a.type=pui.is_touch?"button":"text";pui.a.readOnly=true;pui.a.style.position="absolute";pui.a.style.left="-999px";pui.a.style.top="-999px";pui.a.style.width="10px";pui.a.style.borderStyle="none";pui.a.style.backgroundColor="transparent";pui.runtimeContainer.appendChild(pui.a)}pui.I=true;pui.a.focus();setTimeout(function(){pui.I=
false},0)},1)};pui.addCSS=function(c){var b=document.getElementsByTagName("head")[0],a=document.createElement("style");a.type="text/css";if(pui.is_old_ie)a.styleSheet.cssText=c;else a.innerHTML=c;b.appendChild(a)};
pui.loadCSS=function(c){if(pui.G(c)!=null)return false;var b=document.getElementsByTagName("head")[0],a=document.createElement("link");a.setAttribute("rel","stylesheet");a.setAttribute("type","text/css");a.setAttribute("media","screen");a.setAttribute("href",pui.normalizeURL(c));b.appendChild(a);return true};
pui.removeCSS=function(c){var b=document.getElementsByTagName("head")[0],a=pui.G(c);if(a==null){a=b.getElementsByTagName("style");for(var d=0;d<a.length;d++){var e=a[d];if(e.innerHTML==c||e.styleSheet!=null&&e.styleSheet.cssText==c){b.removeChild(e);return true}}return false}else{b.removeChild(a);return true}};
pui.loadJS=function(c){if(c==null)return null;var b,a,d,e;if(typeof c=="string")b=c;if(typeof c=="object"){b=c.path;a=c.callback;d=c.onerror;e=c.test;if(e!=null&&typeof e=="function"&&e()==true)return false}if(b==null)return null;if(pui.ka(pui.normalizeURL(b))!=null)return false;c=document.getElementsByTagName("head")[0];var h=false,f=document.createElement("script");f.type="text/javascript";f.onreadystatechange=function(){if(f.readyState=="complete"||f.readyState=="loaded")if(!(e!=null&&typeof e==
"function"&&e()!=true)){!h&&a!=null&&a();h=true}};f.onload=function(){if(!(e!=null&&typeof e=="function"&&e()!=true)){!h&&a!=null&&a();h=true}};if(d)f.onerror=d;f.src=pui.normalizeURL(b);c.appendChild(f);return true};
pui.endOfSession=function(c){pui.confirmOnClose=false;pui.shutdownOnClose=false;if(window.puiMobileClient!=null){window.location.href="index.html";c!=null&&pui.alert(c)}else{var b=K().gobackto;if(b!=null){document.body.innerHTML="";c!=null&&pui.alert(c);location.href=b}if(navigator.app!=null&&navigator.app.exitApp!=null){document.body.innerHTML="";c!=null?pui.alert(c,function(){navigator.app.exitApp()}):navigator.app.exitApp()}}};
pui.addUrlCacheBuster=function(c,b){var a=Date.now();if(typeof b==="string"&&b.toLowerCase()!=="get")return c;return c=/[&?]r=[^&]+/.test(c)?c.replace(/([&?]r=)[^&]+/,function(d,e){return e+a}):c+(c.indexOf("?")==-1?"?":"&")+"r="+a};
pui.alert=function(c,b,a,d){if(window.cordova&&window.device.platform=="iOS"&&b==null&&a==null&&d==null)window.alert(c);else if(window.navigator!=null&&window.navigator.notification!=null&&window.navigator.notification.alert!=null)if(b==null&&a==null&&d==null&&window.puiMobileClient!=null&&window.puiMobileClient.alert!=null)window.puiMobileClient.alert(c);else{if(b==null)b=function(){};if(a==null)a="Profound UI";if(d==null)d="OK";window.navigator.notification.alert(c,b,a,d)}else pui.na&&window.parent&&
window.parent!=window&&pui.V(window.parent)&&window.parent.noderun?console.log("Suppressed alert: "+c):alert(c)};pui.applyProperty=function(c,b,a){return window.applyProperty(c,b,a)};pui.get=function(c){return I(D(c,void 0))};
pui.set=function(c,b){var a;a=typeof c=="object"?c:document.getElementById(c);if(a!=null){if(a.tagName=="DIV")if(a.z!=null)a.z.setValue(b);else if(a.comboBoxWidget!=null)a.comboBoxWidget.setValue(b);else if(a.g!=null)a.g.setValue(b);else if(a.button&&a.button.S)a.button.S.innerHTML=b;else if(a.pui&&a.pui.widget)applyProperty(a,"value",b);else a.innerHTML=b;else if(a.tagName=="INPUT"||a.tagName=="SELECT"||a.tagName=="TEXTAREA")if(a.tagName=="INPUT"&&a.type=="checkbox")a.checked=typeof b=="boolean"?
b:a.i!=null&&b==a.i?true:false;else{context=="genie"&&b!=a.value&&pui.d.oa(a);a.value=b}if(context=="dspf"||pui.U&&a.k==null){a.modified=true;pui.va(a);var d=a.wa;if(a.id!=null&&a.id.indexOf(".")==-1&&a.D!=null)pui.ba[a.D]=true;if(d!=null){d.la();d.da=true;pui.ra(a,d.ga())}}if(context=="genie"&&a.k!=null&&a.k.idx!=null)pui.response[a.k.idx]=a;pui.Z(a);if(a.pui&&a.pui.properties)a.pui.properties.value=b}};
pui.getActiveContainer=function(){if(context=="genie"){for(var c=1,b=document.getElementById("window"+c);b;){var a=document.getElementById("window"+ ++c);if(a)b=a;else break}if(b)return b}else if(context=="dspf"&&pui.K)return pui.K;return pui.runtimeContainer};pui.getDisplayType=function(){return pui.U?"5250-handler":context=="dspf"?"rdf":"5250"};
function P(c){function b(){if(!(f>=h.length)){var i=h[f].command,g=h[f].wait;f+=1;if(typeof pui.onPCCommand=="function")try{var j=pui.onPCCommand(i,g);if(j==null||j==true){setTimeout(function(){b()},0);return}}catch(n){showFailureMessage(i)}if(d==1||d==2){j=g?"1":"0";j="http://localhost:"+(typeof pui["pc listener port"]=="number"?pui["pc listener port"]:80)+"/?cmd="+encodeURIComponent(i)+"&wait="+j;if(d==2){j+="&type=image&rnd="+String(Math.random())+String((new Date).getTime());g=new Image;g.onload=
function(){b()};g.onerror=function(){console.log("PC Command Listener m2 failure.");a(i)};g.src=j}else{j=new pui.Ajax(j);j.method="GET";j.async=g?false:true;j.suppressAlert=true;j.onfail=function(p){if(p.c()!=200){console.log("PC Command Listener comm. failure: "+p.v());a(i)}};j.onsuccess=function(){b()};try{j.send()}catch(k){console.log("PC Command Listener failure.",k);a(i)}}}else if(d==3)C({url:J("PUI0009117.pgm"),method:"post",params:{cmd:i,auth:pui.appJob&&pui.appJob.auth?pui.appJob.auth:""},
async:true,handler:function(p){if(p!=null)if(p.cmd){p="puilaunch:"+encodeURIComponent(p.cmd);var l=document.createElement("iframe");l.style.display="none";l.src=p;document.body.appendChild(l);setTimeout(function(){l!=null&&l.parentNode!=null&&document.body.removeChild(l);l=null;b()},5E3)}else p.error&&console.log("PC Command signing error:",p.error);else console.log("Empty response from PC command signing program.")}});else{if(f==0&&h.length>0){g=[];for(j=0;j<h.length;j++)g.push("("+h[j].aa+")");
i=g.join(" && ")}try{e.runCommand(i)}catch(s){g='Unable to execute "'+i+'".\n\n';if(s!=null)g+=s.name+":\n\n"+s.message+".";alert(g)}}}}function a(i){console.log("Command: "+i);i=pui.getLanguageText("runtimeMsg","pccommand error");pui["alert pccommand errors"]!==false?alert(i):console.log(i);console.log("Visit https://docs.profoundlogic.com/x/aQFK for more information on supporting STRPCCMD.")}var d=1;if(pui["use pc listener"])d=1;if(window.HTTPS!=null&&window.HTTPS=="ON"&&d==1)d=2;if(pui["pc listener mode"])d=
parseInt(pui["pc listener mode"]);if(typeof pui["pc command mode"]=="string")switch(pui["pc command mode"]){case "applet":d=0;break;case "listener":d=1;break;case "listener_m2":d=2;break;case "launcher":d=3;break;default:d=1;console.log("Unsupported pc command mode:",pui["pc command mode"])}if(d==0){var e=document.getElementById("PCCommandApplet");if(!e){pui.q=c;loadPCCommandApplet("runCommandCb");return}}var h=[],f=0;h=typeof c=="string"?[{command:c,wait:false}]:c;b()}
window.runCommandCb=function(){P(pui.q);pui.q=null};pui.runPCCommand=P;pui.isServerBusy=function(){if(typeof context=="undefined")return false;if(context=="dspf"&&pui.o===false||context=="genie"&&pui.d.h===true)return true;for(var c=document.getElementsByTagName("iframe"),b=0;b<c.length;b++){var a=c[b].contentWindow;if(a!=null){var d=null;try{d=a.pui}catch(e){}if(d!=null)if(typeof d==="object")if(typeof d.isServerBusy==="function")if(d.isServerBusy())return true}}return false};
pui.showLastError=function(){if(errors.length==0)alert("No errors have been reported.");else{var c=errors.length-1;alert("Operation: "+errors[c].pa+"\nId: "+errors[c].id+"\n\nMessage: "+errors[c].text+"\n"+errors[c].ua)}};
pui.editCode=function(c,b){function a(t,x){var y=["","","","nn/n","nn/nn","nn/nn/n","nn/nn/nn","nnn/nn/nn","nn/nn/nnnn","nnn/nn/nnnn"];if(i.dateEdit==="*ymd"){y[8]="nnnn/nn/nn";y[9]="nnnnn/nn/nn"}y=y[v];t=String(t);t=t.replace(".","");t=t.replace(",","");t=t.replace("-","");t="0000000000"+t;t=t.substr(t.length-x);var L="/";if(i.dateEditSeparator!=null)L=i.dateEditSeparator;for(var G=false,M=0,N="",F=0;F<y.length;F++){var B=y.substr(F,1),Q=y.substr(F+1,1);if(B==="/"||Q==="/")G=true;if(B==="/")B=L;
else{B=t.substr(M,1);M+=1;if(B==="0")G||(B=" ");else G=true}N+=B}return N}function d(t,x,y){for(t+="";t.length<x;)t+=y;return t}var e=null,h=0,f=null,i={},g=2;if(typeof arguments[g]==="number"){e=arguments[g];g++;if(typeof arguments[g]==="number"){h=arguments[g];g++}}if(typeof arguments[g]==="string"){f=arguments[g];g++}if(typeof arguments[g]==="object"){i=arguments[g];g++}var j=false;if(f==="*astfill"){j=true;f=null}var n=false,k=null,s=false,p=g=false;g=" ";if(pui.appJob&&typeof pui.appJob.decimalFormat===
"string")g=pui.appJob.decimalFormat;var l=g==="I"||g==="J",o=g==="J";if(i.decimalEdit!=null){l=i.decimalEdit===","||i.decimalEdit==="0,";o=i.decimalEdit==="0."||i.decimalEdit==="0,"}if(b>="1"&&b<="4")k="999.00";if(b>="A"&&b<="D")k="999.00CR";if(b>="J"&&b<="M")k="999.00-";if(b>="N"&&b<="Q")k="-999.00";if(b=="1"||b=="A"||b=="J"||b=="N"||b=="2"||b=="B"||b=="K"||b=="O")s=true;g=b=="1"||b=="A"||b=="J"||b=="N"||b=="3"||b=="C"||b=="L"||b=="P"?true:false;if(b=="Z")k="999.00";if(b==="X"||b==="Z")p=true;if(b===
"X")n=true;b>="5"&&b<="9"&&pui.alert("User-defined edit code not supported: "+b+".");b>="1"&&b<="9"||b>="A"&&b<="D"||b>="J"&&b<="Q"||b>="X"&&b<="Z"||pui.alert("Invalid edit code: "+b+".");var m=(c||0)+"",r=parseFloat(m,10)||0,q;q=m.replace(/\..*/,"");if(q==="-0")q="-";if((q==""||q=="-")&&o)q="0";var u;u=m;if(u.indexOf(".")==-1)u+=".";u=u.replace(/.*\./,"");var v=q.length;if(v<3)v=3;var w=u.length;if(typeof e==="number")v=e;if(typeof h==="number")w=h;if(b=="Y"){if(v<3||v>9)pui.alert("Length not valid for edit code Y.");
return a(r,v)}e=".";if(l)e=",";if(p)e="";if(w>0){u=d(u,w,"0");if(q==="0"&&!o)q="";m=q+e+u}var E=" ";if(n)E="0";if(j)E="*";if(s){for(h=/(\d+)(\d{3})/;h.test(q);)q=q.replace(h,"$1"+(l?".":",")+"$2");m=q+(w>0?e+u:"");l=v-w-1;l=l>=0?l:0}l=r<0;m=m.replace(/-/g,"");if(k==="(999.00)"){if(l)m="("+m+")"}else if(k==="999.00-")m+=l?"-":" ";else if(k==="999.00CR")m+=l?"CR":"  ";else if(k==="-999.00")if(l)m="-"+m;if(f)m=f=="EUR"?m+" EUR":f=="$"?m.substr(0,1)=="-"?"-"+f+m.substr(1):f+m:f+m;if(!g)if(r===0)m="";
(function(){var t=v;t+=w&&!p?1:0;if(s)t+=parseInt((v-w-1)/3);if(k==="999.00CR")t+=2;if(k==="999.00-")t+=1;if(k==="-999.00")t+=1;if(typeof f==="string")t+=f.length;var x=m;for(x+="";x.length<t;)x=E+x;m=x})();return m};
pui.editWord=function(c,b,a){function d(){if(o.length>0){var q=o.substr(o.length-1,1);o=o.substr(0,o.length-1);if(q=="0"&&o.length==0&&r)q=m?"*":" "}else{q="0";if(r)q=" ";if(m)q="*"}return q}c=String(c);var e={};if(typeof a==="object")e=a;a="$";if(e.currencySymbol!=null)a=e.currencySymbol;var h=b.indexOf("0")+1,f=b.indexOf("*")+1;if(h==0||f!=0&&f<h)h=f;for(var i=-1,g=b.length-1;g>=0;g-=1)if(g+1==h||b.substr(g,1)==" "){i=g;break}f=b.substr(0,i+1);var j="",n="",k=false,s=false,p=b.substr(i+1).indexOf("-")>=
0||b.substr(i+1).indexOf("CR")>=0;for(g=i+1;g<b.length;g++){var l=b.substr(g,1);if(b.substr(g,2)=="CR"){s=true;g++}else if(l=="-")s=true;else if(l!="&")if(!(l=="*"&&!s))if(l.toUpperCase()>="A"&&l.toUpperCase()<="Z"&&p&&!s)b=b.substr(0,g)+" "+b.substr(g+1);else{j=b.substring(i+1,g);n=b.substr(g);k=true;break}}k||(j=b.substr(i+1));g=".";l=" ";if(pui.appJob&&typeof pui.appJob.decimalFormat==="string")l=pui.appJob.decimalFormat;if(typeof e.decimalFormat==="string")l=e.decimalFormat;if(l==="I"||l==="J")g=
",";e=0;g=f.split(g);if(g.length>1)e=g[1].replace(/[^ ]/g,"").length;var o;o=isNaN(Number(c))?"0":String(c);o=o.replace("-","");g=o.split(".");l=g[0];b="";i=null;if(g.length>1)b=g[1];if(i==null||isNaN(i))i=e;for(;b.length>i;)b=b.substr(0,b.length-1);for(;i>b.length;)b+="0";for(o=l+b;o.substr(0,1)=="0";)o=o.substr(1);e="";var m=i=false;var r=b=false;if(h==0)r=true;for(g=f.length-1;g>=0;g-=1){k=l=f.substr(g,1);if(l==" ")k=d();else if(l=="&")k=" ";else if(l=="0"&&g+1==h)k=d();else if(l=="*"){m=true;
k=d()}else if(l==a){if(g+2==h){k=d();b=true}}else if(i){k=" ";if(m)k="*"}e=k+e;if(g<=h)r=true;if(r&&o.length==0)i=true}j=j.replace(/&/g," ");j=j.replace(/\*/g," ");if(c>=0){j=j.replace("CR","  ");j=j.replace("-"," ")}e=e+j+n;c=e.length-1;e=H(e);if(m&&e.substr(0,1)!="*")e="*"+e;if(b)e=a+e;a=0;if(e[e.length-1]==="-")a=1;for(;e.length<=c;)e=" "+e;return e};
pui.getRadioGroupValue=function(c){if(typeof c!=="string")return null;if(typeof pui.w!=="object")return null;for(var b=null,a=pui.currentFormatNames,d=a.length-1;d>=0;d--){var e=a[d].toUpperCase()+"."+c.toUpperCase();if(typeof pui.w[e]!=="undefined"){b=pui.w[e];break}}if(b==null)return null;c=null;for(a=0;a<b.length;a++){d=b[a];if(d.checked&&d.radioValue!=null){c=d.radioValue;break}}return c};pui.R=function(){for(var c=document.getElementById("auth-form"),b=document.cookie.split("; "),a=false,d=0;d<b.length;d++){var e=b[d].split("=");if(unescape(e[0])=="pui-signon-"+c.action)if(unescape(e[1])=="1"){a=true;break}}if(typeof Storage!="undefined"){b=K();if(b.workstnid)sessionStorage["atrium-params-workstnid"]=b.workstnid;else try{delete sessionStorage["atrium-params-workstnid"]}catch(h){}if(b.suffixid)sessionStorage["atrium-params-suffixid"]=b.suffixid;else try{delete sessionStorage["atrium-params-suffixid"]}catch(f){}if(b.duplicateid)sessionStorage["atrium-params-duplicateid"]=
b.duplicateid;else try{delete sessionStorage["atrium-params-duplicateid"]}catch(i){}}if(a)location.href=c.action;else{if(a=document.getElementById("auth-box"))a.style.display="";c.elements["auth-user"].focus()}};
pui.Q=function(){var c=document.getElementById("auth-form"),b=c.elements["auth-user"].value,a=c.elements["auth-password"].value,d=document.getElementById("auth-message");d.innerHTML="";if(I(b)==""){d.innerHTML=authMessages["user required"];c.elements["auth-user"].focus();return false}else if(I(a)==""){d.innerHTML=authMessages["password required"];c.elements["auth-password"].focus();return false}pui.j(function(){var e=new pui.Ajax("/profoundui/pui0005010.pgm");e.async=true;e.method="POST";pui.setReqAuth(e,
b,a);e.suppressAlert=true;e.onready=function(h){if(h.c()==200){var f=eval("("+h.e()+")");h=f.days;var i=false;if(f.warn==true)if(h==0){f=authMessages["password expired"];pui.alert(f);i=true}else{f=authMessages["password pending expiration"];f=f.replace(/{DAYS}/g,h);i=confirm(f)}if(i){h="/profoundui/changepass";h+="?user="+encodeURIComponent(b);h+="&next="+encodeURIComponent(c.action);h+="&back="+encodeURIComponent(location.href);location.href=h}else{document.cookie=escape("pui-signon-"+c.action)+
"=1; path=/";location.href=c.action}}else{d.innerHTML=authMessages["invalid credentials"];c.elements["auth-user"].focus()}};e.send()});return false};pui.j=function(c){var b=new pui.Ajax("/profoundui/pui0005010.pgm");b.async=typeof c==="function"?true:false;b.method="POST";pui.setReqAuth(b,"PUI_SIGNOFF_USER","PUI_SIGNOFF_USER");b.suppressAlert=true;if(typeof c==="function")b.onready=function(){typeof c=="function"&&c()};b.send()};window.pui.signOn=pui.Q;window.pui.clearCredentials=pui.j;
window.pui.signOnInit=pui.R;pui.P=function(){var c=K(),b=document.getElementById("change-user"),a=document.getElementById("change-current"),d=b,e=document.getElementById("change-cancel");if(typeof c.user!="undefined"){b.value=c.user.toUpperCase();b.readOnly=true;b.className+=" read-only";d=a}if(typeof c.back=="undefined")e.style.display="none";document.getElementById("change-box").style.display="block";d.focus()};pui.O=function(){var c=K();if(typeof c.back!="undefined")location.href=c.back};
pui.C=function(){var c=K(),b=document.getElementById("change-form"),a=b.elements["change-user"].value,d=b.elements["change-current"].value,e=b.elements["change-new"].value,h=b.elements["change-confirm"].value,f=document.getElementById("change-message");f.innerHTML="";if(I(a)==""){f.innerHTML=passMessages["user required"];b.elements["change-user"].focus();return false}else if(I(d)==""){f.innerHTML=passMessages["current required"];b.elements["change-current"].focus();return false}else if(I(e)==""){f.innerHTML=
passMessages["new required"];b.elements["change-new"].focus();return false}else if(I(h)==""){f.innerHTML=passMessages["confirm required"];b.elements["change-confirm"].focus();return false}else if(e!=h){f.innerHTML=passMessages["must match"];b.elements["change-new"].focus();return false}h=new pui.Ajax("/profoundui/pui0005011.pgm");h.async=true;h.method="POST";h.params={};h.params.user=a;h.params.current=d;h.params["new"]=e;h.suppressAlert=true;h.onready=function(i){if(i.c()!=200){f.innerHTML="HTTP "+
i.c()+" - "+i.l()+".";b.elements["change-user"].focus()}else{var g;try{g=eval("("+i.e()+")");if(typeof g.success!="boolean")throw"";if(!g.success&&typeof g.error!="string")throw"";}catch(j){g={};g.success=false;g.error="The server response is missing or invalid."}if(g.success==false){f.innerHTML=g.error;b.elements["change-user"].focus()}else{pui.alert(passMessages.success);pui.j(function(){var n=new pui.Ajax("/profoundui/pui0005010.pgm");n.async=true;n.method="POST";pui.setReqAuth(n,a,e);n.suppressAlert=
true;n.onready=function(k){if(k.c()==200){if(typeof c.next!="undefined")location.href=c.next}else{pui.alert("HTTP "+k.c()+" - "+k.l()+".");b.elements["change-user"].focus()}};n.send()})}}};h.send();return false};
pui.setReqAuth=function(c,b,a){var d=navigator.userAgent.indexOf("Edge")!=-1,e=!d&&navigator.userAgent.indexOf("Chrome")!=-1;d=!d&&navigator.userAgent.indexOf("Safari")!=-1&&!e;var h=navigator.userAgent.indexOf("Firefox")!=-1;if(d||e||h){c.user=encodeURIComponent(b);c.password=encodeURIComponent(a)}else{c.user=b;c.password=a}};window.pui.passInit=pui.P;window.pui.passCancel=pui.O;window.pui.changePass=pui.C;
